name: pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types:
    - mirror_sync

concurrency: 
  group: "pages"
  cancel-in-progress: true

env:
  download_dir: download/manjaro-sway

jobs:
  pages:
    environment:
      name: website
      url: https://manjaro-sway.download
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
    - name: download background image
      run: |
        curl -s https://raw.githubusercontent.com/Manjaro-Sway/manjaro-sway-wallpapers/master/static/gruvbox-dark-manjarosway-3840x2160.png > docs/background.png
        curl -s https://mirror.manjaro-sway.download/manjaro-sway/release.json > docs/release.json
    - name: deploy website to cf pages
      uses: cloudflare/wrangler-action@4c10c1822abba527d820b29e6333e7f5dac2cabd # 2.0.0
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages publish --project-name=manjaro-sway ./docs
